Repository Kong/go-kong, pull requests merged in 2022-12, with the labels that each got.

#241 ci: add one CI step that requires all tests to pass
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/ci

#240 chore: add kong 3.1.0 to CI
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/maintenance, area/ci

#247 chore: add pre-flight license check
  .github/workflows/integration-test-enterprise.yaml
Labels: area/ci

#249 ci: use one go version on CI
  .github/workflows/golangci-lint.yml
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/ci

#235 feat: add oauth2 client_type field
  kong/credentials.go
  kong/oauth2_auth_service_test.go
  kong/zz_generated.deepcopy.go
Labels: enhancement

#253 fix(tests): fix flaky MarkUnhealthy tests
  kong/target_service_test.go
Labels: area/tests

#254 fix: add codecov token to avoid failures in upload process
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/ci, area/tests

#252 feat: add Client.ReloadDeclarativeConfig()
  CHANGELOG.md
  kong/client.go
  kong/config_service.go
  kong/config_service_test.go
  kong/request.go
  kong/request_test.go
  kong/test_utils.go
Labels: enhancement
