Repository Kong/go-kong, pull requests merged in 2023-04, with the labels that each got.

#306 chore: bump kong versions in integration tests strategy matrix
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/maintenance, area/ci

#310 chore: retract v0.39.1
  go.mod
Labels: area/maintenance

#299 feat: add FillID method for Service, Route and Consumer
  CHANGELOG.md
  kong/ids.go
  kong/ids_test.go
Labels: enhancement

#318 chore: prepare release 0.41.0
  CHANGELOG.md
Labels: area/maintenance

#319 chore: add RELEASE.md
  RELEASE.md
Labels: area/maintenance
