Repository Kong/go-kong, pull requests merged in 2023-01, with the labels that each got.

#263 test: remove TestRunWhenEnterprise
  kong/client_test.go
Labels: area/tests

#264 feat: add IsForbiddenErr error checking for 403s
  kong/error.go
  kong/error_test.go
  kong/test_utils.go
Labels: enhancement

#269 ci: set workflow status to failed when tests fail or get cancelled
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/maintenance, area/ci
