Repository Kong/go-kong, pull requests merged in 2023-06, with the labels that each got.

#341 ci: use project defined golangci-lint version
  .gitignore
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/golangci-lint.go
Labels: area/maintenance

#347 chore(ci): update gateway images in CI
  .ci/setup_kong.sh
  .ci/setup_kong_ee.sh
  .github/workflows/integration-test-enterprise.yaml
  .github/workflows/integration-test.yaml
Labels: area/maintenance, area/ci

#349 chore(build): get rid of obsolete Go build tags
  kong/admin_service_test.go
  kong/mtls_auth_service_test.go
  kong/workspace_service_test.go
  third_party/golangci-lint.go
  tools/tools.go
Labels: area/maintenance

#354 feat: config helper
  CHANGELOG.md
  kong/client.go
  kong/client_test.go
Labels: enhancement
